### ISSUE TITLE
Error of not setting required primitive-typed argument not being caught

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/barclay#101]
First seen in a GATKSparkTool.
If an argument of a tool is marked as `required` but has a primitive type, e.g. `int`, when a user invokes the tool without providing the required argument, the expected error message is NOT seen, and the tool proceeds to run.
 
It seems that the default value for that argument (appropriate according to its type) is silently set.

**Comment by cmnbroad** [comment]
Closing as this is a dup of https://github.com/broadinstitute/barclay/issues/23.

**Comment by SHuang-Broad** [comment]
Thanks @cmnbroad !
So would you recommend that avoid using primitive types for required arguments for now, for GATK tool developers?

**Comment by cmnbroad** [comment]
@SHuang-Broad Yes, for required arguments its best to avoid primitive types for now.

**Comment by cmnbroad** [comment]
Closing as a dup of #23.
