### ISSUE TITLE
Tag 2.0.0 tag does not appear in releases

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/barclay#129]
In GATK 4.0.0.0 and current Picard Tools, the version of Barclay in use is 2.0.0 - nevertheless, I cannot see to which commit this tag correspond.

@cmnbroad - can you pleas add the tag. I would like to track which changes happen since the previous release to be sure if I can update to the latest before 2.0.0. Thank you!

**Comment by cmnbroad** [comment]
Yeah sorry, looks like I forgot to push the tag up. Done.
