### ISSUE TITLE
CommandLinePluginDescriptor.includePluginClass() flipped?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/barclay#131]
In CommandLinePluginDescriptor, shouldnt includePluginClass be:

getPluginBaseClass().isAssignableFrom(c)

not 

c.isAssignableFrom(getPluginBaseClass())

as it is now?

**Comment by cmnbroad** [comment]
Yes, good catch. We recently changed this part of the interface, and all of the exiting test cases had override implementations, so I think there is no test coverage for the default. We should flip it and add a test that exercises it.
