### ISSUE TITLE
Ability to have "shoort or long options" passed as args to jopt parser

### ISSUE THREAD

**Issue by smutalik** [broadinstitute/barclay#140]
I do not see an option to provide an option like below:

-a "-b true -c false" -d "-e true"

This is a tracking issue for the same.

**Comment by magicDGS** [comment]
I believe that `-a "-b true -c false" -d "-e true"`, parsed values are `a="-b true -c false"` and `d="-e true"` if they are defined as string. Are you referring to that, or that they should be parsed differently?

**Comment by cmnbroad** [comment]
@smutalik I'm guessing this was issue was meant for the jop-simple repo ?

**Comment by cmnbroad** [comment]
Closing on the assumption this question was meant for jopt-simple, not Barclay. Feel free to re-open if thats incorrect!
