### ISSUE TITLE
Should max/min values be Comparable<> instead of double?

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/barclay#16]
I noticed that the min/max value in the `@Argument` are all specified as `double`.  Would it make more sense to take `Comparable<?>` since that would allow any sort of ordered input to be bounded?

**Comment by cmnbroad** [comment]
It would be nice to generalize if there is a use case for it (there are very few instances where these are actually used in gatk3, but maybe its because they're not general enough). I'm also not sure what it would look like since AFAIK you cant use an interface type in an annotation.

**Comment by lbergelson** [comment]
Oh, good point about the interface type in the annotation, I forgot it was basically primitives only.

**Comment by cmnbroad** [comment]
Closing this; various related discussions happening in https://github.com/broadinstitute/barclay/issues/30 and https://github.com/broadinstitute/barclay/issues/31. Feel free to reopen if this is still relevant.
