### ISSUE TITLE
Question about iterating LinkedHashMap in Freemarker

### ISSUE THREAD

**Issue by pgrt** [broadinstitute/barclay#168]
Hi,

While packaging version 4.0.0 in Debian, I had to change the iterating on the _outputs_ variable in src/main/resources/org/broadinstitute/barclay/helpTemplates/wdlToolTemplate.wdl.ftl, as two build-time tests were not passing, due to a syntax error in the above-cited file ('>' unexpected at 382, 37, got ',').

I solved the issue with the enclosed patch. You may see if it can be useful for you.

Best,
Pierre
[fix_iterating_in_template.txt](https://github.com/broadinstitute/barclay/files/5210191/fix_iterating_in_template.txt)

**Comment by cmnbroad** [comment]
@pgrt Thanks for the patch. The proposed changed seems fine, but I'm unclear why the existing template fails. The freemarker doc seems to indicate that the current syntax is perfectly valid for hashes, and it works for us in both Barclay and GATK. Do you have any insight into why you see this failure but we don't, or why its needed ?

**Comment by pgrt** [comment]
Hi,
Thanks for your reply, I'm happy I could help!
Unfortunately, I am not really able to say why I needed this change. Maybe we have some old software in Debian and your way of iterating is fine for new version? Or the opposite? I don't have enough knowledge about Freemarker.
I see you issued a pull request, I hope it will be fine :)
