### ISSUE TITLE
Does barclay support tagging arguments as incompatible? 

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/barclay#5]
Let's say we have a tool that accepts two arguments, each is fine separately but they can't be provided together because the corresponding functionality is incompatible. Is there a way I can tag these arguments? How and what exactly happens if I do invoke them both?

**Comment by droazen** [comment]
See `Argument.mutex()` in barclay.

**Comment by vdauwera** [comment]
Ah, "mutually exclusive", splendid.

**Comment by cmnbroad** [comment]
You can see an example usage in GATK [here](https://github.com/broadinstitute/gatk/blob/dd7e19a58fece8d165f5f8d2d17f88ad3ddf2666/src/main/java/org/broadinstitute/hellbender/tools/picard/sam/MergeBamAlignment.java#L43).

**Comment by vdauwera** [comment]
Perfect, thank you!
