### ISSUE TITLE
HelpDoclet cannot be used directly

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/barclay#55]
Although the javadoc states that  `this class can be used to generate documentation directly`, that's not the case because if used in a gradle task (e.g. onlineDoc) it complains with the following error:

```
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:cleanOnlineDoc
:onlineDoc
javadoc: error - Doclet class org.broadinstitute.barclay.help.HelpDoclet does not contain a start method
1 error
:onlineDoc FAILED
```

It seems that it is because it requires a public static method called start, as in the GATK Doctlet or in the Picard one. I'm planing to have my own doctlet, but while testing how this work it will be nice to be able to use the minimal implementation...

**Comment by magicDGS** [comment]
Also, it should be mention that the implementation of that method is required for a working implementation.

**Comment by cmnbroad** [comment]
Yeah, that protocol is defined by javadoc, and as you mentioned, the method is static, so it can't be overridden. So I think we just need to change the doc.
