### ISSUE TITLE
Allow a different output extension for the index file

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/barclay#59]
I'm in the case in which I would like to have a different format for the index than the rest of components for use with jekyll: 1) index as an yml data file for iterate over different components,  and 2) markdown to render for each component.

It will be nice to have a new option for the index extension, which by default should be the same as the component extension. Someone have any objection to this?

**Comment by cmnbroad** [comment]
@magicDGS Sounds reasonable to me.
