### ISSUE TITLE
@Hidden, @Advanced annotations are not handled by command line parser

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/barclay#6]
I don't see any handling of annotations for arguments:

* `@Hidden`: I expect that it hides the option from help, but not for the argument parsing.
* `@Advance`: I expect this option to appear under an especial category pointing out that they should be used with caution. I think that another interesting way for this advance options could be an argument in `SpecialArgumentsCollection` to show the "advance" help.

**Comment by cmnbroad** [comment]
@magcDGS You're right - Hidden and Advanced should both be handled specially in the command line usage output.

**Comment by cmnbroad** [comment]
We should also integrate min/max and recommended values as well (assuming they're integrated as part of the docgen changes to @Argument).

**Comment by cmnbroad** [comment]
These annotations and properties all need to be reflected/honored in both parsing and usage output.

**Comment by cmnbroad** [comment]
Partially fixed (for max/min values) via https://github.com/broadinstitute/barclay/pull/11. Still need to do the Hidden/Advanced part.
