### ISSUE TITLE
JSON output file names should not include the output file extension

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/barclay#72]
For example, if the output extension is "html", the JSON files are currently called "workunit.html.json". This behavior was carried over from GATK3, but is unnecessary and a little misleading. The work unit output format and extension are independent of JSON, so the JSON file should just be called "workunit.json".

**Comment by vdauwera** [comment]
Yeah that was a bug in my implementation in GATK3. Would be great to fix it.

**Comment by magicDGS** [comment]
PR opened: #74
