### ISSUE TITLE
Update Barclay for other file output types (i.e. bash tab-completion, WDL, etc.)

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/barclay#81]
In order to support generating tab-completion files for command-line usage and WDL files, some minor changes will need to be made to Barclay - specifically how it prepares data for ingestion by FreeMarker.

A good test will include some new templates and tests to prove that the output is what is expected.

**Comment by jonn-smith** [comment]
I goofed and numbered my branch according to the issue numbers in the gatk repo.

Anyway... the branch associated with this is jts_tab_completion_1454

**Comment by cmnbroad** [comment]
@jonn-smith I think this is done and can be closed ?

**Comment by jonn-smith** [comment]
@cmnbroad yup.
