### ISSUE TITLE
Populate javadoc see tags into the extraDocs

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/barclay#83]
If the `@see` tag in the javadoc contains a `@DocumentedFeature` class, it will be nice to populate it into the extraDocs to obtain the urls easily.

**Comment by cmnbroad** [comment]
My vote would be to keep the model simple, and not try to automate this. Someone (either Barclay or the user) would need to think about how to handle duplicate/redundant extraDoc references, and there would be side-effects to adding/removing @see tags and extraDocs links. I'd much prefer to embrace the difference between the javadoc and the userdoc; have it be explicit in the source code; and not require the documenter or Barclay think about rules/side effects when making changes.

**Comment by vdauwera** [comment]
Can you guys provide a few mocked up examples of what the potential solutions would look like from the point of view of the documenter? I have to admit that right now the discussion is just a little too abstract for me to really grasp.

**Comment by magicDGS** [comment]
Closing in favor of #85, where I tried to summarize the problems and my suggestions in a better way.
