### ISSUE TITLE
DocumentedFeatures do not populate arguments

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/barclay#97]
After https://github.com/broadinstitute/barclay/commit/78b17117c264df3a39a1e29a3bf34f323b900eab, even if a documented feature has a non-arg constructor (such as `ReadFilter`), the arguments are not populated into the JSON nor in the property map. This is because they are not annotated with the `CommandLineProgramProperties`.

Maybe it should be enforced by Barclay to have every documented feature with a non-arg constructor, or have a marker for such a argument container.

**Comment by cmnbroad** [comment]
@magicDGS Thanks for catching that. And it illustrates why we so badly need the mock test framework and good unit tests. I'm going to try to catch up on some of those old PRs this week.

**Comment by magicDGS** [comment]
I did a PR with the fix for this, but I'll wait until the mock test framework is in to add the tests.
